"""add college info fields from master data

Revision ID: 019f842f61b1
Revises: 90911bc0ea1a
Create Date: 2026-07-18 18:07:36.855575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '019f842f61b1'
down_revision: Union[str, Sequence[str], None] = '90911bc0ea1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colleges', sa.Column('status', sa.String(), nullable=True))
    op.add_column('colleges', sa.Column('established', sa.String(), nullable=True))
    op.add_column('colleges', sa.Column('website', sa.String(), nullable=True))
    op.add_column('colleges', sa.Column('place', sa.String(), nullable=True))
    op.add_column('colleges', sa.Column('naac_rating', sa.String(), nullable=True))
    op.add_column('colleges', sa.Column('fees', sa.String(), nullable=True))
    op.add_column('colleges', sa.Column('hostel_available', sa.String(), nullable=True))
    op.add_column('colleges', sa.Column('students_placed_last_year', sa.Integer(), nullable=True))
    op.add_column('colleges', sa.Column('highest_package', sa.String(), nullable=True))
    op.add_column('colleges', sa.Column('average_package', sa.String(), nullable=True))
    op.add_column('colleges', sa.Column('companies_visited', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('colleges', 'companies_visited')
    op.drop_column('colleges', 'average_package')
    op.drop_column('colleges', 'highest_package')
    op.drop_column('colleges', 'students_placed_last_year')
    op.drop_column('colleges', 'hostel_available')
    op.drop_column('colleges', 'fees')
    op.drop_column('colleges', 'naac_rating')
    op.drop_column('colleges', 'place')
    op.drop_column('colleges', 'website')
    op.drop_column('colleges', 'established')
    op.drop_column('colleges', 'status')
    # ### end Alembic commands ###
