"""add category seats table

Revision ID: 2f70e5e2db63
Revises: bbb60a21354b
Create Date: 2026-07-20 15:07:03.188896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f70e5e2db63'
down_revision: Union[str, Sequence[str], None] = 'bbb60a21354b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('choice_code', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('general_seats', sa.Integer(), nullable=True),
    sa.Column('ladies_seats', sa.Integer(), nullable=True),
    sa.Column('total_seats', sa.Integer(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_seats')
    # ### end Alembic commands ###
