"""add PWD DEF EWS TFWS seat columns

Revision ID: 329e41c10cd4
Revises: 2f70e5e2db63
Create Date: 2026-07-22 13:37:36.238021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '329e41c10cd4'
down_revision: Union[str, Sequence[str], None] = '2f70e5e2db63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_seats', sa.Column('pwd_seats', sa.Integer(), nullable=True))
    op.add_column('category_seats', sa.Column('def_seats', sa.Integer(), nullable=True))
    op.add_column('category_seats', sa.Column('ews_seats', sa.Integer(), nullable=True))
    op.add_column('category_seats', sa.Column('tfws_seats', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category_seats', 'tfws_seats')
    op.drop_column('category_seats', 'ews_seats')
    op.drop_column('category_seats', 'def_seats')
    op.drop_column('category_seats', 'pwd_seats')
    # ### end Alembic commands ###
