"""add level and percentile to cutoffs

Revision ID: 8cd48a248895
Revises: dd8b0c6b133a
Create Date: 2026-07-24 10:17:47.315065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cd48a248895'
down_revision: Union[str, Sequence[str], None] = 'dd8b0c6b133a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cutoffs', sa.Column('level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cutoffs', 'level')
    # ### end Alembic commands ###
