"""add capacity and college code columns

Revision ID: 90911bc0ea1a
Revises: 94d57fb4d172
Create Date: 2026-07-18 15:21:41.945830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90911bc0ea1a'
down_revision: Union[str, Sequence[str], None] = '94d57fb4d172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('capacity', sa.Integer(), nullable=True))
    op.add_column('colleges', sa.Column('code', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'colleges', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'colleges', type_='unique')
    op.drop_column('colleges', 'code')
    op.drop_column('branches', 'capacity')
    # ### end Alembic commands ###
